### ISSUE TITLE
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.0)

### ISSUE THREAD

**Issue by pablomendezroyo** [gnosischain/gbc-deposit-ui#3]
Hey, a few dappnode users are experiencing the following error while uploading the deposit data file
```
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.0)
```

I was wondering if the gnosis network was created with an outdated RPC, if so the UI should update to the latest RPC so users add the network gnosis to their wallet manager with a valid RPC

**Comment by kvakes** [comment]
![Screenshot from 2022-06-15 11-33-42](https://user-images.githubusercontent.com/377005/173812333-44465f00-64bd-4aca-8c35-c8b582e848c0.png)

**Comment by Juan-cc** [comment]
Even after updating RPC url on Metamask we can't use deposit app. I found it uses old rpc internally:
![image](https://user-images.githubusercontent.com/16144265/173822961-ccd50422-b69d-41ae-a13c-d809c34bc720.png)

**Comment by Mojmir-R** [comment]
That is correct @Juan-cc, as Igor confirmed above, deposit DApp will be redeployed to address this.

**Comment by maxaleks** [comment]
Should be fixed now.
