### ISSUE TITLE
Validator Status tab doesn't work

### ISSUE THREAD

**Issue by kvakes** [gnosischain/gbc-deposit-ui#5]
![Screenshot from 2022-06-15 16-13-03](https://user-images.githubusercontent.com/377005/173849281-94432caa-f296-4891-8466-b4ff51cd0795.png)

**Comment by Juan-cc** [comment]
I am facing same issue

**Comment by maxaleks** [comment]
@kvakes @Juan-cc please provide a `deposit_data.json` file so that I can reproduce the issue
