### ISSUE TITLE
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.0)

### ISSUE THREAD

**Issue by chrisdotn** [gnosischain/gbc-deposit-ui#7]
With deposit.gnosischain.com, I can't claim the validators on the DAppNode tab. 

**Steps to reproduce**
1. Configure Gnosis chain in Metamask (settings from gnosisscan.io)
```
{
   rpcUrl: "https://rpc.gnosischain.com", 
   chainId: 100, 
   symbol: "xDai", 
   explorer: "https://gnosisscan.io"
}
```
2. Upload `deposit_data.json` on the DAppNode tab

**Expected Result**
Claim succeeds

**Actual Result**
The website stays in _Validating_ and then shows the error msg: `could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)`

**Additional Notes**
1. The browser console shows that the website is trying to connect to https://rpc-deposit.gnosischain.com/, which seems to be unreachable. The error in the console is: `OPTIONS https://rpc-deposit.gnosischain.com/ CORS Missing Allow Origin`.
2. This issue is a duplicate of #3, which has been resolved in June. The issue now seems to resurface.

**Comment by rogue15raccoon** [comment]
Having same issue as above.

**Comment by seopolis** [comment]
I confirm this bug. I tried to claim mine and I always get this error.

**Comment by pablomendezroyo** [comment]
Can you make sure you are using the right rpc? it should be  https://rpc.gnosischain.com 

See https://metamask.zendesk.com/hc/en-us/articles/360052711572-How-to-connect-to-the-Gnosis-Chain-network-formerly-xDai-

**Comment by pablomendezroyo** [comment]
@maxaleks hey! looks like the RPC used by this UI is down, could you re-up it or put another one available please?

**Comment by maxaleks** [comment]
@pablomendezroyo hey! I no longer have access to the app on Heroku. You can change the value of `REACT_APP_RPC_URL` there and then redeploy the app.

**Comment by chrisdotn** [comment]
I can confirm that switching to a working RPC node does the trick. I've cloned the repo, changed the RPC node to https://rpc.gnosischain.com (instead of ~~https://rpc-deposit.gnosischain.com~~) and it worked for me.

**Comment by pablomendezroyo** [comment]
Gnosis team says the RPC has been updated, it should work now
